# Generated by Django 5.2.8 on 2025-12-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication_inventory_app', '0008_alter_patientmedication_days_to_take_medicine_and_more'),
        ('patient_staff_app', '0004_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(help_text='The specific date and time the dose is due.')),
                ('is_given', models.BooleanField(default=False)),
                ('time_given', models.DateTimeField(blank=True, null=True)),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_administering_medication', to='patient_staff_app.patientassignment')),
                ('medication_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedule', to='medication_inventory_app.patientmedication')),
                ('patient_given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication_schedule', to='patient_staff_app.patient')),
            ],
            options={
                'verbose_name': 'Medication Schedule',
            },
        ),
    ]
