# Generated by Django 5.2.8 on 2025-12-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationschedule',
            name='given_by',
        ),
        migrations.RemoveField(
            model_name='medicationschedule',
            name='is_given',
        ),
        migrations.RemoveField(
            model_name='medicationschedule',
            name='time_given',
        ),
    ]
