# Generated by Django 5.2.8 on 2025-12-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_staff_app', '0004_loginhistory'),
        ('scheduling_app', '0002_remove_medicationschedule_given_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_remainder_sent', models.BooleanField(default=False)),
                ('remainder_response', models.TextField()),
                ('remainder_message', models.TextField(default='\n                Hello, kindly administer to: \n                    Patient Name: <django.db.models.fields.related.ForeignKey>,\n                    Medication: <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7f81de5990>,\n                    Scheduled at: <django.db.models.query_utils.DeferredAttribute object at 0x7f81bb2910>,\n                    Quantity per dose: <django.db.models.query_utils.DeferredAttribute object at 0x7f81bb1b90>\n                ')),
                ('is_given', models.BooleanField(default=False)),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_to_giv_medication', to='patient_staff_app.patientassignment')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_to_take_medication', to='scheduling_app.medicationschedule')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_phone_number', to='patient_staff_app.healthworker')),
            ],
        ),
    ]
