# Generated by Django 5.2.8 on 2025-12-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_notificationdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdashboard',
            name='remainder_message',
            field=models.TextField(default='\n                Hello, kindly administer to: \n                    Patient Name: <django.db.models.fields.related.ForeignKey>,\n                    Medication: <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7f7d9264d0>,\n                    Scheduled at: <django.db.models.query_utils.DeferredAttribute object at 0x7f7d926810>,\n                    Quantity per dose: <django.db.models.query_utils.DeferredAttribute object at 0x7f7d925ad0>\n                '),
        ),
    ]
