# Generated by Django 5.2.8 on 2025-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0004_alter_notificationdashboard_remainder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdashboard',
            name='remainder_message',
            field=models.TextField(default='\n                Hello, kindly administer to: \n                    Patient Name: <django.db.models.fields.related.ForeignKey>,\n                    Medication: <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7fb4f4f810>,\n                    Scheduled at: <django.db.models.query_utils.DeferredAttribute object at 0x7fb4f4e050>,\n                    Quantity per dose: <django.db.models.query_utils.DeferredAttribute object at 0x7fb57e4950>\n                '),
        ),
    ]
