# Generated by Django 5.2.8 on 2025-12-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_staff_app', '0004_loginhistory'),
        ('scheduling_app', '0005_alter_notificationdashboard_remainder_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationdashboard',
            old_name='is_remainder_sent',
            new_name='is_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='notificationdashboard',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='notificationdashboard',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='notificationdashboard',
            name='remainder_message',
        ),
        migrations.RemoveField(
            model_name='notificationdashboard',
            name='remainder_response',
        ),
        migrations.AddField(
            model_name='notificationdashboard',
            name='reminder_message',
            field=models.TextField(default='Hello, kindly administer to:\nPatient: {patient_name}\nMedication: {medication}\nScheduled at: {scheduled_time}\nDose: {dose_quantity}'),
        ),
        migrations.AddField(
            model_name='notificationdashboard',
            name='reminder_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdashboard',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling_app.medicationschedule'),
        ),
        migrations.AlterField(
            model_name='notificationdashboard',
            name='health_worker',
            field=models.ForeignKey(blank=True, help_text='The caregiver assigned to receive this reminder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='patient_staff_app.healthworker'),
        ),
    ]
