# Generated by Django 5.2.8 on 2025-12-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0006_rename_is_remainder_sent_notificationdashboard_is_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdashboard',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling_app.medicationschedule'),
        ),
    ]
