# Generated by Django 5.2.8 on 2025-12-11 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0008_alter_notificationdashboard_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdashboard',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling_app.medicationschedule'),
            preserve_default=False,
        ),
    ]
