# Generated by Django 5.2.7 on 2025-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0013_alter_notificationdashboard_reminder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdashboard',
            name='reminder_message',
            field=models.TextField(default='Hello, kindly administer to:\nPatient: {patient_name}\nMedication: {medication}\nScheduled at: {scheduled_time}\nDose: {dose_quantity} {dosage_unit}'),
        ),
    ]
