# Generated by Django 5.2.7 on 2025-12-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_staff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthworker',
            options={'permissions': [('can_view_patient_assignments', 'Can view the patients he/she is assigned to'), ('can_edit_assigned_patient_medication', 'Can add/update assigned patient medication')], 'verbose_name': 'Health Worker Profile'},
        ),
    ]
