# Generated by Django 5.2.7 on 2025-12-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_staff_app', '0002_alter_healthworker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthworker',
            options={'permissions': [('can_view_patient_assignments', 'Can view the patients he/she is assigned to')], 'verbose_name': 'Health Worker Profile'},
        ),
    ]
