# Generated by Django 5.2.8 on 2025-12-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_staff_app', '0004_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('medication_form', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('dosage_unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_dose', models.PositiveIntegerField()),
                ('days_to_take_medicine', models.PositiveIntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dosage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication_inventory_app.medication')),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_for_patient', to='medication_inventory_app.medication')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication', to='patient_staff_app.patient')),
            ],
        ),
    ]
