# Generated by Django 5.2.8 on 2025-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='patientmedication',
            options={'verbose_name': 'Patient Medication'},
        ),
    ]
