# Generated by Django 5.2.8 on 2025-12-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_inventory_app', '0002_alter_medication_options_and_more'),
        ('patient_staff_app', '0004_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedication',
            name='health_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_assigned', to='patient_staff_app.patientassignment'),
        ),
    ]
