# Generated by Django 5.2.8 on 2025-12-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_inventory_app', '0005_alter_patientmedication_health_worker'),
        ('patient_staff_app', '0004_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedication',
            name='health_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_assigned', to='patient_staff_app.patientassignment'),
        ),
    ]
