# Generated by Django 5.2.8 on 2025-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_inventory_app', '0006_alter_patientmedication_health_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedication',
            name='dosage_unit',
            field=models.CharField(help_text='Unit of the medicine (mg, ml, tablet)', max_length=20),
        ),
    ]
