# Generated by Django 5.2.8 on 2025-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_inventory_app', '0007_alter_patientmedication_dosage_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedication',
            name='days_to_take_medicine',
            field=models.PositiveIntegerField(help_text='Total number of days the patient takes the medicine'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='quantity_per_dose',
            field=models.PositiveIntegerField(help_text='How many units the patient takes per day'),
        ),
    ]
